In [1]:
import numpy as np

In [ ]:
# 1. Create a 1D NumPy array containing numbers from 1 to 10.

In [6]:
q1 = np.arange(1, 11)
print(q1)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# 2. Create a NumPy array using the list [5, 10, 15, 20, 25].

In [5]:
q2 = np.array([5, 10, 15, 20, 25])
print(q2)

[ 5 10 15 20 25]


In [ ]:
# 3. Create an array of 10 zeros.

In [7]:
q3 = np.zeros(10)
print(q3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 4. Create an array of 8 ones.

In [8]:
q4 = np.ones(8)
print(q4)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# 5. Create an array using arange() from 0 to 20 with step 2.

In [9]:
q5 = np.arange(0, 20, 2)
print(q5)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
# 6. Create an array using linspace() with 5 values between 10 and 50.

In [10]:
q6 = np.linspace(10, 50, 5)
print(q6)

[10. 20. 30. 40. 50.]


In [ ]:
# 7. Create a 3 × 3 matrix filled with zeros.

In [12]:
q7 = np.zeros((3, 3))
print(q7)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 8. Create a 4 × 4 matrix filled with ones.

In [13]:
q8 = np.ones((4, 4))
print(q8)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 9. Create a 2 × 5 array containing numbers from 1 to 10 using reshape()

In [14]:
q9 = np.arange(1, 11).reshape(2, 5)
print(q9)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# 10. Create a 3 × 4 array with numbers from 1 to 12.

In [15]:
q10 = np.arange(1, 13).reshape(3, 4)
print(q10)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
arr1d = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(arr1d)

[10 20 30 40 50 60 70 80]


In [ ]:
# 11. Print the first element of the array.

In [18]:
q11 = arr1d[0]
print(q11)

10


In [ ]:
# 12. Print the last element of the array.

In [19]:
q12 = arr1d[-1]
print(q12)

80


In [ ]:
# 13. Print the 4th element of the array.

In [20]:
q13 = arr1d[3]
print(q13)

40


In [ ]:
# 14. Print the element at index position 2.

In [21]:
q14 = arr1d[2]
print(q14)

30


In [ ]:
# 15. Print the element at index position 5.

In [22]:
q15 = arr1d[5]
print(q15)

60


In [ ]:
# 16. Print the element at index position 6.

In [23]:
q16 = arr1d[6]
print(q16)

70


In [ ]:
# 17. Print the element at index position 3.

In [24]:
q17 = arr1d[3]
print(q17)

40


In [ ]:
# 18. Create the given 2D NumPy array

In [25]:
q18 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(q18)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 19. Create a 4 × 3 matrix with numbers from 1 to 12.

In [26]:
q19 = np.arange(1, 13).reshape(4, 3)
print(q19)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# 20. Create a 5 × 2 matrix with numbers from 1 to 10.

In [27]:
q20 = np.arange(1, 11).reshape(5, 2)
print(q20)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [28]:
arr2d = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

In [ ]:
# 21. Print the element 50.

In [29]:
q21 = arr2d[1, 1]
print(q21)

50


In [ ]:
# 22. Print the element 30.

In [30]:
q22 = arr2d[0, 2]
print(q22)

30


In [ ]:
# 23. Print the element 70.

In [31]:
q23 = arr2d[2, 0]
print(q23)

70


In [ ]:
# 24. Print the first row of the array.

In [32]:
q24 = arr2d[0]
print(q24)

[10 20 30]


In [ ]:
# 25. Print the second column of the array.

In [33]:
q25 = arr2d[:, 1]
print(q25)

[20 50 80]
