In [1]:
import numpy as np

In [6]:
q1 = np.arange(1, 11)
print(q1)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
q2 = np.array([5, 10, 15, 20, 25])
print(q2)

[ 5 10 15 20 25]


In [7]:
q3 = np.zeros(10)
print(q3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
q4 = np.ones(8)
print(q4)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
q5 = np.arange(0, 20, 2)
print(q5)

[ 0  2  4  6  8 10 12 14 16 18]


In [10]:
q6 = np.linspace(10, 50, 5)
print(q6)

[10. 20. 30. 40. 50.]


In [12]:
q7 = np.zeros((3, 3))
print(q7)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
q8 = np.ones((4, 4))
print(q8)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
q9 = np.arange(1, 11).reshape(2, 5)
print(q9)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
q10 = np.arange(1, 13).reshape(3, 4)
print(q10)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
arr1d = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(arr1d)

[10 20 30 40 50 60 70 80]


In [18]:
q11 = arr1d[0]
print(q11)

10


In [19]:
q12 = arr1d[-1]
print(q12)

80


In [20]:
q13 = arr1d[3]
print(q13)

40


In [21]:
q14 = arr1d[2]
print(q14)

30


In [22]:
q15 = arr1d[5]
print(q15)

60


In [23]:
q16 = arr1d[6]
print(q16)

70


In [24]:
q17 = arr1d[3]
print(q17)

40


In [25]:
q18 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(q18)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
q19 = np.arange(1, 13).reshape(4, 3)
print(q19)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
q20 = np.arange(1, 11).reshape(5, 2)
print(q20)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [28]:
arr2d = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

In [29]:
q21 = arr2d[1, 1]
print(q21)

50


In [30]:
q22 = arr2d[0, 2]
print(q22)

30


In [31]:
q23 = arr2d[2, 0]
print(q23)

70


In [32]:
q24 = arr2d[0]
print(q24)

[10 20 30]


In [33]:
q25 = arr2d[:, 1]
print(q25)

[20 50 80]
