In [5]:
import numpy as np

### 1. Daily website visitors: print ndim, shape, size, dtype

In [4]:
q1 = np.array([120, 150, 180, 200, 170])
print(q1)
print(q1.ndim, q1.shape, q1.size, q1.dtype)

[120 150 180 200 170]
1 (5,) 5 int64


### 2. Employee IDs from 101 to 110

In [5]:
q2 = np.arange(101, 111)
print(q2)

[101 102 103 104 105 106 107 108 109 110]


### 3. 3x3 matrix for product sales with values 1–9

In [ ]:
q3 = np.arange(1, 10).reshape(3, 3)
print(q3)

### 4. Fixed monthly subscription fee of 999 for 5 users

In [6]:
q4 = np.full(5, 999)
print(q4)

[999 999 999 999 999]


### 5. 4x4 array of server downtime minutes initialized with 0

In [7]:
q5 = np.zeros((4, 4), dtype=int)
print(q5)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### 6. 3x3 matrix of successful API responses initialized with 1

In [8]:
q6 = np.ones((3, 3), dtype=int)
print(q6)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### 7. Order IDs from 1000 to 1020 with step 2

In [9]:
q7 = np.arange(1000, 1021, 2)
print(q7)

[1000 1002 1004 1006 1008 1010 1012 1014 1016 1018 1020]


### 8. Customer purchase amounts

In [10]:
q8 = np.array([2500, 3200, 1500, 4200, 2800])
print(q8)

[2500 3200 1500 4200 2800]


### 9. Convert list of app ratings into a NumPy array

In [11]:
q9 = np.array([4, 5, 3, 4, 5])
print(q9)

[4 5 3 4 5]


### 10. 12 months sales values (1–12)


In [6]:
q10 = np.arange(1, 13)
print(q10)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## 2. Indexing & Filtering – Data Analytics (11–20)

### 11. 3rd day's revenue

In [13]:
revenue_daily = np.array([12000, 15000, 18000, 20000, 17000])
q11 = revenue_daily[2]
print(q11)

18000


### 12. Extract values from index 2 to 4

In [14]:
purchases = np.array([500, 1200, 750, 300, 900, 1500])
q12 = purchases[2:5]
print(q12)

[750 300 900]


### 13. Reverse weekly website traffic

In [15]:
traffic = np.array([1000, 1200, 1100, 1500, 1400, 1300])
q13 = traffic[::-1]
print(q13)

[1300 1400 1500 1100 1200 1000]


### 14. Print the last three transactions

In [16]:
transactions = np.array([450, 600, 700, 900, 1200, 1500])
q14 = transactions[-3:]
print(q14)

[ 900 1200 1500]


### 15. Extract every second order amount

In [17]:
orders = np.array([200, 400, 600, 800, 1000, 1200])
q15 = orders[::2]
print(q15)

[ 200  600 1000]


### 16. Prices greater than 2000

In [18]:
prices = np.array([1200, 2500, 3000, 800, 1500])
q16 = prices[prices > 2000]
print(q16)

[2500 3000]


### 17. Extract even quantities

In [19]:
quantities = np.array([1, 2, 3, 4, 5, 6, 7, 8])
q17 = quantities[quantities % 2 == 0]
print(q17)

[2 4 6 8]


### 18. Expenses greater than 20000

In [20]:
expenses = np.array([12000, 15000, 18000, 22000, 25000, 30000])
q18 = expenses[expenses > 20000]
print(q18)

[22000 25000 30000]


### 19. Replace response times > 500 ms with 0

In [21]:
response_times = np.array([120, 450, 600, 700, 300])
response_times[response_times > 500] = 0
q19 = response_times
print(q19)

[120 450   0   0 300]


### 20. Count orders greater than 1000

In [22]:
order_values = np.array([500, 1200, 750, 2000, 1500])
q20 = np.sum(order_values > 1000)
print(q20)

3


## 3. 2D Arrays – Business Reports (21–30)

In [8]:
matrix_2d = np.array([
    [100, 120, 140],
    [150, 160, 170],
    [200, 210, 220]
])

### 21. Print the second store sales

In [24]:
q21 = matrix_2d[1]
print(q21)

[150 160 170]


### 22. Print sales of Product C across stores (column index 2)

In [25]:
q22 = matrix_2d[:, 2]
print(q22)

[140 170 220]


### 23. Print the sales value at row 2 column 3 (0-indexed: row 1, col 2)

In [11]:
q23 = matrix_2d[1, 2]
print(q23)

170


### 24. Replace the center sales value with 999

In [12]:
matrix_copy = matrix_2d.copy()
matrix_copy[1, 1] = 999
q24 = matrix_copy
print(q24)

[[100 120 140]
 [150 999 170]
 [200 210 220]]


### 25. Extract sales data of first two stores

In [13]:
q25 = matrix_2d[:2, :]
print(q25)

[[100 120 140]
 [150 160 170]]


### 26. Extract sales of the last product (last column)

In [14]:
q26 = matrix_2d[:, -1]
print(q26)

[140 170 220]


### 27. Find all sales values greater than 160

In [15]:
q27 = matrix_2d[matrix_2d > 160]
print(q27)

[170 200 210 220]


### 28. Total sales per store (row sum)

In [16]:
q28 = np.sum(matrix_2d, axis=1)
print(q28)

[360 480 630]


### 29. Total sales per product (column sum)

In [17]:
q29 = np.sum(matrix_2d, axis=0)
print(q29)

[450 490 530]


### 30. Maximum sales value per store

In [18]:
q30 = np.max(matrix_2d, axis=1)
print(q30)

[140 170 220]


# 4. Reshaping Arrays – Analytics Data (31–35)

### 31. 12 months revenue into a 3x4 quarterly matrix

In [19]:
q31 = np.arange(1, 13).reshape(3, 4)
print(q31)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 32. Convert matrix to 1D revenue array

In [20]:
matrix_rev = np.array([[1000, 2000, 3000], [4000, 5000, 6000]])
q32 = matrix_rev.reshape(-1)
print(q32)

[1000 2000 3000 4000 5000 6000]


### 33. 16 hourly server requests reshaped into a 4x4 matrix

In [21]:
q33 = np.arange(1, 17).reshape(4, 4)
print(q33)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### 34. Convert a 3x4 sales matrix into a 4x3 matrix

In [22]:
matrix_3x4 = np.arange(1, 13).reshape(3, 4)
q34 = matrix_3x4.reshape(4, 3)
print(q34)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### 35. Flatten the product sales matrix

In [23]:
sales_matrix = np.array([[120, 150], [200, 250], [300, 350]])
q35 = sales_matrix.flatten()
print(q35)

[120 150 200 250 300 350]


### 36. Add daily orders from two platforms

In [24]:
p1 = np.array([100, 200, 300])
p2 = np.array([50, 150, 250])
q36 = p1 + p2
print(q36)

[150 350 550]


# 5. Mathematical Operations – Business Metrics (36–42)

### 37. Increase product prices by multiplying with tax factor 1.1

In [25]:
base_prices = np.array([1000, 2000, 3000])
q37 = base_prices * 1.1
print(q37)

[1100. 2200. 3300.]


### 38. Square of customer purchase quantities

In [26]:
qty = np.array([2, 3, 4, 5])
q38 = qty ** 2
print(q38)

[ 4  9 16 25]


### 39. Calculate profit by subtracting cost from revenue

In [27]:
rev = np.array([5000, 6000, 7000])
cost = np.array([3000, 3500, 4000])
q39 = rev - cost
print(q39)

[2000 2500 3000]


### 40. Calculate discounted prices by dividing by 2

In [28]:
orig_prices = np.array([2000, 4000, 6000])
q40 = orig_prices / 2
print(q40)

[1000. 2000. 3000.]


### 41. Find the total daily revenue

In [29]:
daily_rev = np.array([12000, 15000, 18000, 20000])
q41 = np.sum(daily_rev)
print(q41)

65000


### 42. Find maximum and minimum product prices

In [30]:
prod_prices = np.array([450, 1200, 700, 300, 900])
q42_max = np.max(prod_prices)
q42_min = np.min(prod_prices)
print("Max:", q42_max, "| Min:", q42_min)

Max: 1200 | Min: 300


# 6. Statistical Operations – Data Analytics (43–47)

### 43. Average daily sales

In [31]:
sales_data = np.array([12000, 15000, 18000, 20000, 17000])
q43 = np.mean(sales_data)
print(q43)

16400.0


### 44. Median customer purchase value

In [32]:
purchase_vals = np.array([500, 700, 900, 1200, 1500])
q44 = np.median(purchase_vals)
print(q44)

900.0


### 45. Variance of monthly revenue

In [33]:
monthly_rev = np.array([10000, 12000, 14000, 16000])
q45 = np.var(monthly_rev)
print(q45)

5000000.0


### 46. Standard deviation of product ratings

In [34]:
ratings = np.array([3, 4, 5, 4, 5])
q46 = np.std(ratings)
print(q46)

0.7483314773547882


### 47. Total revenue from a 3x3 sales matrix

In [35]:
sales_3x3 = np.array([[100, 120, 140], [150, 160, 170], [200, 210, 220]])
q47 = np.sum(sales_3x3)
print(q47)

1470


# 7. Searching & Unique Values – Analytics (48–50)

### 48. Index of the highest product price

In [36]:
item_prices = np.array([1200, 2500, 3000, 800, 1500])
q48 = np.argmax(item_prices)
print(q48)

2


### 49. Index of lowest order value

In [37]:
order_vals = np.array([500, 1200, 750, 2000, 1500])
q49 = np.argmin(order_vals)
print(q49)

0


### 50. Find unique product categories

In [38]:
categories = np.array(["electronics", "fashion", "electronics", "grocery", "fashion"])
q50 = np.unique(categories)
print(q50)

['electronics' 'fashion' 'grocery']
