In [2]:
import numpy as np

In [5]:
a3=np.arange(1,17)
print(a3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [9]:
a1=a3.reshape(4,4)
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [18]:
a4=a1[:2,:2]
print(a4)

[[1 2]
 [5 6]]


In [21]:
a5=a1[2:,2:]
print(a5)

[[11 12]
 [15 16]]


In [38]:
a5=a1[:,1:3]
print(a5)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


#np.ones
#np.zeros

In [40]:
d3=np.arange(1,37)
print(d3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [42]:
n1 = np.random.randint(10)
print(n1)

6


In [ ]:
# Create an array of 100 elements 1-100
# 3 check array attributes ndin, shape, size,dtype
# sum max min mean std var

# reshape 2d,3d possible 2 combinations

# extract 4 submatrrix

In [44]:
q1=np.arange(1,101)
print(q1)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [45]:
q2=q1.reshape(10,10)
print(q2)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [78]:
q4=q1.reshape(4,25)
print(q4)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20  21  22  23  24  25]
 [ 26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43
   44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
   69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
   94  95  96  97  98  99 100]]


In [46]:
q3=q1.reshape(4,5,5)
print(q3)

[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]]

 [[ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]
  [ 46  47  48  49  50]]

 [[ 51  52  53  54  55]
  [ 56  57  58  59  60]
  [ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]]

 [[ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]
  [ 96  97  98  99 100]]]


In [79]:
q5=q1.reshape(5,5,4)
print(q5)

[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]
  [ 13  14  15  16]
  [ 17  18  19  20]]

 [[ 21  22  23  24]
  [ 25  26  27  28]
  [ 29  30  31  32]
  [ 33  34  35  36]
  [ 37  38  39  40]]

 [[ 41  42  43  44]
  [ 45  46  47  48]
  [ 49  50  51  52]
  [ 53  54  55  56]
  [ 57  58  59  60]]

 [[ 61  62  63  64]
  [ 65  66  67  68]
  [ 69  70  71  72]
  [ 73  74  75  76]
  [ 77  78  79  80]]

 [[ 81  82  83  84]
  [ 85  86  87  88]
  [ 89  90  91  92]
  [ 93  94  95  96]
  [ 97  98  99 100]]]


In [49]:
print(q1.ndim)
print(q2.ndim)
print(q3.ndim)

1
2
3


In [51]:
print(q1.shape)
print(q2.shape)
print(q3.shape)

(100,)
(10, 10)
(4, 5, 5)


In [54]:
print(q1.size)
print(q2.size)
print(q3.size)

100
100
100


In [56]:
print(q1.dtype)
print(q2.dtype)
print(q3.dtype)

int64
int64
int64


### Submatrix for 2D

In [62]:
q2

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [61]:
w1=q2[:2,:2]
print(w1)

[[ 1  2]
 [11 12]]


In [63]:
w2=q2[:3,3:6]
print(w2)

[[ 4  5  6]
 [14 15 16]
 [24 25 26]]


In [67]:
w3=q2[:,1:3]
print(w3)

[[ 2  3]
 [12 13]
 [22 23]
 [32 33]
 [42 43]
 [52 53]
 [62 63]
 [72 73]
 [82 83]
 [92 93]]


In [69]:
w2=q2[1:9,2:6]
print(w2)

[[13 14 15 16]
 [23 24 25 26]
 [33 34 35 36]
 [43 44 45 46]
 [53 54 55 56]
 [63 64 65 66]
 [73 74 75 76]
 [83 84 85 86]]


### Submatrix for 3D

In [71]:
q3

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25]],

       [[ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75]],

       [[ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

In [73]:
w5=q3[0,:4,:2]
print(w5)

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]


In [75]:
w6=q3[3,3:6]
print(w6)

[[ 91  92  93  94  95]
 [ 96  97  98  99 100]]


In [76]:
w6=q3[2,1:6]
print(w6)

[[56 57 58 59 60]
 [61 62 63 64 65]
 [66 67 68 69 70]
 [71 72 73 74 75]]


In [77]:
w7=q3[:,1:3]
print(w3)

[[ 2  3]
 [12 13]
 [22 23]
 [32 33]
 [42 43]
 [52 53]
 [62 63]
 [72 73]
 [82 83]
 [92 93]]
