### Advance indexing

In [1]:
import numpy as np

In [2]:
q1 = np.arange(1,11)
print(q1)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
a1 = np.array([[12,13,14],[15,16,17]])
print(a1)

[[12 13 14]
 [15 16 17]]


In [10]:
a2 = ([10,20,30])
print(a2)


[10, 20, 30]


In [6]:
a1+a2

array([[22, 33, 44],
       [25, 36, 47]])

In [16]:
a3 = q1.reshape(2,5)
print(a3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [18]:
a5 = np.array([[22],[27]])
print(a5)

[[22]
 [27]]


In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.vstack((a,b))
print(result)

[[1 2 3]
 [4 5 6]]


In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.hstack((a,b))
print(result)

[1 2 3 4 5 6]


In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.row_stack((a,b))
print(result)

[[1 2 3]
 [4 5 6]]


C:\Users\HP\AppData\Local\Temp\ipykernel_31500\1080786708.py:4: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  result = np.row_stack((a,b))


In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.column_stack((a,b))
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [25]:
print(np.__version__)

2.4.6


In [30]:
num = int(input("Enter the number:"))
for i in range(1,11):
    value = num * i
    print(f"{num} * {i} = {value}")


Enter the number: 5


5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50
